#!/usr/bin/env python3
"""Generate docs/API.md from live responses of the running data (FastAPI TestClient; no server needed).

python tools/gen_api_docs.py
Long arrays are trimmed to their first items and long strings shortened, so the file shows shapes, not data dumps.
"""
from __future__ import annotations

import json
import sqlite3
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from fastapi.testclient import TestClient  # noqa: E402

from backend.app import CONN, app  # noqa: E402


def trim(o, depth=0):
    if isinstance(o, list):
        return [trim(x, depth + 1) for x in o[:2]] + (["..."] if len(o) > 2 else [])
    if isinstance(o, dict):
        return {k: trim(v, depth + 1) for k, v in o.items()}
    if isinstance(o, str) and len(o) > 160:
        return o[:157] + "..."
    return o


def block(title: str, method: str, path: str, note: str, body) -> str:
    return (f"### {method} `{path}`\n\n{note}\n\n```json\n{json.dumps(trim(body), indent=1, ensure_ascii=False)}\n```\n")


def main() -> None:
    c = TestClient(app)
    dec = c.get("/api/decisions").json()
    did = dec[0]["decision_id"]
    card = c.get(f"/api/decisions/{did}").json()
    mid = card["evidence"][0]["message_id"]
    cl = c.get("/api/clusters").json()
    qa = CONN.execute("SELECT answer_json FROM qa_log ORDER BY id DESC LIMIT 1").fetchone()
    ask_example = json.loads(qa[0]) if qa else {"note": "ask a question once to populate this example"}
    nd = CONN.execute("SELECT answer_json FROM qa_log WHERE answer_json LIKE '%\"status\": \"no_decision\"%' "
                      "ORDER BY id DESC LIMIT 1").fetchone()
    parts = [
        "# Precedent API\n",
        "Generated by `tools/gen_api_docs.py` from real responses (arrays trimmed to 2 items, long strings shortened).",
        "Base URL `http://127.0.0.1:8000`. All GET endpoints accept `?redact=1` to mask emails, phone numbers and IBANs.",
        "Statuses: `active` | `superseded` | `amended` | `contested`. Decision types: `explicit` | `implicit`.\n",
        "## Read\n",
        block("health", "GET", "/api/health", "Liveness, demo mode flag, model per role.", c.get("/api/health").json()),
        block("stats", "GET", "/api/stats", "Counter strip, funnel and cost panel.", c.get("/api/stats").json()),
        block("decisions", "GET", "/api/decisions?status=&q=&from=&to=&cluster=&type=",
              "Ledger list. `status` may be comma-separated.", dec),
        block("decision", "GET", "/api/decisions/{decision_id}",
              "Decision Drawer: evidence (with `forwarded`, `original_author`), history chain, edges, topic current "
              "state, confidence label with explanation.", card),
        block("clusters", "GET", "/api/clusters", "Topic lanes for the Timeline.", cl),
        block("cluster", "GET", "/api/clusters/{cluster_id}", "One lane with its decisions and edges.",
              c.get(f"/api/clusters/{cl[0]['cluster_id']}").json() if cl else {}),
        block("graph", "GET", "/api/graph", "Nodes (with `lane`), edges and lanes for the lifecycle view.",
              c.get("/api/graph").json()),
        block("conflicts", "GET", "/api/conflicts", "Contested topics, both sides with evidence.",
              c.get("/api/conflicts").json()),
        block("email", "GET", "/api/emails/{message_id}",
              "URL-encode the message id (it contains `<`, `@`, `>`). Returns the split text and the thread.",
              c.get("/api/emails/" + urllib.parse.quote(mid, safe="")).json()),
        "### GET `/api/eval/latest`\n\nScorecard export written by `python -m eval.run` (shape: "
        "`{generated_at, git_commit, banner, targets, global, models, splits: {dev, holdout}}`; each split has metric "
        "fields, `decisions_table`, `qa`, `edges`, `conflicts`, `near_decisions`). 404 until an evaluation has run.\n",
        "## Ask\n",
        block("ask", "POST", "/api/ask  body {\"question\": \"...\"}",
              "Cited answer. Replace `[^n]` in `answer_md` with citation chips from `citations`. Show `confidence` "
              "(deterministic), not `model_confidence`. 503 in demo mode for questions that were never asked.",
              ask_example),
    ]
    if nd:
        parts.append(block("ask-no-decision", "POST", "/api/ask (no_decision example)",
                           "`status: no_decision` renders the 'No decision found' state with `closest`.",
                           json.loads(nd[0])))
    parts += [
        "## Write\n",
        "### POST `/api/decisions/{decision_id}/dispute`  body `{\"note\": \"...\"}`\n\nHuman-in-the-loop feedback. "
        "Returns `{\"ok\": true}`.\n",
        "### POST `/api/ingest` (multipart field `files`: .eml files, a .zip, or an .mbox)\n\nStarts a run; returns "
        "`{\"run_id\", \"files\"}`. 409 in demo mode or while a run is in progress.\n",
        "### POST `/api/ingest/corpus`\n\nRuns the full pipeline over the bundled corpus; returns `{\"run_id\"}`.\n",
        "### GET `/api/runs/{run_id}/events` (Server-Sent Events)\n\nEvents (each `data:` is JSON with `event`, "
        "`run_id`, `ts`): `stage_start {stage}`, `progress {stage, done, total}`, `stage_done {stage, ...stats}`, "
        "`decision_found {decision_id|record_id, text, date, status?}`, `run_done {summary}`, `error {message}`. "
        "Late subscribers get the full history replayed. `GET /api/runs/{run_id}` returns status + last 50 events.\n",
        "### POST `/api/demo/load`  body `{\"enabled\": true|false}`\n\nLoads `demo/cached_run.sqlite` and goes "
        "offline (or turns demo mode off). Returns `{\"demo_mode\": bool}`.\n",
    ]
    out = ROOT / "docs" / "API.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
